[env:tm-device-858]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM3
upload_speed = 921600 ;115200
monitor_port = COM3
monitor_speed = 115200

build_flags = 
	-I include

lib_deps = 
	esp-arduino-libs/ESP32_Button@^0.0.1
	https://github.com/jreue/tm-shared.git#1.0.16
	